version: '3.8'
services:
  mongo-user:
    image: mongo
    container_name: mongo-user
    ports:
      - "27017:27017"
    volumes:
      - mongo-user-data:/data/db

  user-service:
    build:
      context: ./microservices/user-service
    container_name: user-service
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo-user:27017/userdb
      - JWT_SECRET=your_super_secret
    depends_on:
      - mongo-user

  mongo-product:
    image: mongo
    container_name: mongo-product
    ports:
      - "27018:27017"
    volumes:
      - mongo-product-data:/data/db

  mongo-cart:
    image: mongo
    container_name: mongo-cart
    ports:
      - "27019:27017"
    volumes:
      - mongo-cart-data:/data/db

  mongo-order:
    image: mongo
    container_name: mongo-order
    ports:
      - "27020:27017"
    volumes:
      - mongo-order-data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  mongo-user-data:
  mongo-product-data:
  mongo-cart-data:
  mongo-order-data:
