services:
  mongo-user:
    image: mongo
    container_name: mongo-user
    ports:
      - "27021:27017" 
    volumes:
      - mongo-user-data:/data/db

  user-service:
    build:
      context: ./microservices/user-service
    container_name: user-service
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo-user:27017/userdb
      - JWT_SECRET=your_super_secret
    depends_on:
      - mongo-user

  mongo-product:
    image: mongo
    container_name: mongo-product
    ports:
      - "27018:27017"
    volumes:
      - mongo-product-data:/data/db

  product-service:
    build:
      context: ./microservices/product-service
    container_name: product-service
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - MONGO_URI=mongodb://mongo-product:27017/products
    depends_on:
      - mongo-product

  mongo-cart:
    image: mongo
    container_name: mongo-cart
    ports:
      - "27019:27017"
    volumes:
      - mongo-cart-data:/data/db

  cart-service:
    build:
      context: ./microservices/cart-service
    container_name: cart-service
    ports:
      - "5003:5003"
    environment:
      - PORT=5003
      - MONGO_URI=mongodb://mongo-cart:27017/carts
    depends_on:
      - mongo-cart

  mongo-order:
    image: mongo
    container_name: mongo-order
    ports:
      - "27020:27017"
    volumes:
      - mongo-order-data:/data/db

  order-service:
    build:
      context: ./microservices/order-service
    container_name: order-service
    ports:
      - "5002:5002"
    environment:
      - PORT=5002
      - MONGO_URI=mongodb://mongo-order:27017/orders
    depends_on:
      - mongo-order
      - order-rabbitmq

  order-rabbitmq:
    image: rabbitmq:3-management
    container_name: order-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  mongo-user-data:
  mongo-product-data:
  mongo-cart-data:
  mongo-order-data: